---
- name: Ensure site.fact exists
  stat:
    path: /etc/ansible/facts.d/site.fact
  register: fact_file

- name: Read patch compliance status
  command: cat /etc/ansible/facts.d/site.fact
  when: fact_file.stat.exists
  register: site_fact_raw
  changed_when: false

- name: Get patchcompliance line from site.fact
  shell: "grep patchcompliance /etc/ansible/fact.d/site.fact | awk -F '\"' '{print $4}'"
  register: patch_output
  changed_when: false
  when: fact_file.stat.exists

- name: Set patch compliance fact
  set_fact:
    patch_compliance: "{{ patch_output.stdout | default('Unknown') }}"
  when: patch_output is defined


- name: Collect server info
  set_fact:
    server_report:
      ip: "{{ ansible_host }}"
      name: "{{ ansible_hostname }}"
      os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
      kernel: "{{ ansible_kernel }}"
      uptime: "{{ (ansible_uptime_seconds | int // 3600) }} hrs {{ ((ansible_uptime_seconds | int % 3600) // 60) }} mins"
      compliance: "{{ patch_compliance | default('Not Available') }}"

- name: Create report directory
  delegate_to: localhost
  file:
    path: /tmp/compliance_report
    state: directory
    mode: '0755'

- name: Add host data to hostvars file
  delegate_to: localhost
  copy:
    dest: "/tmp/compliance_report/{{ inventory_hostname }}.json"
    content: "{{ server_report | to_nice_json }}"

- name: Generate Excel report
  delegate_to: localhost
  script: files/generate_excel_report.py
